### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by fenollp** [beardedeagle/alpine-erlang-builder#17]
Why create/use this project when https://hub.docker.com/_/erlang exists?

I'm genuinely curious as docker hub stdlib is at least:
* maintained somewhat officially: https://github.com/erlang/docker-erlang-otp/blob/e2e804aeeb6e6bc5fd49f66481be1dff829428f5/21/alpine/Dockerfile
* up to date (it's got 21.2.2 on alpine 3.8)
* builds are pretty reproducible (locked dependencies)
* more than one arch is supported/pre-built

I don't mean to be an ass but I saw you announcing this project on the Erlang slack. Why?

**Comment by beardedeagle** [comment]
- I tend to release at a far more accelerated pace
- My images are always up to date with not _ONLY_ the latest OTP and alpine release, but the latest rebar releases and os deps
- My images use libressl over openssl
- My images are vastly smaller than the "official" images
- This is for primarily for an app I own and release at work, I just open sourced all of my images incase people want to use them
- I plan to automate this entire thing and add additional builds/arches in the near future
